language: haskell

sudo: false
cache:
  directories:
  - $HOME/.stack/
  - $HOME/.local/

before_install:
 - mkdir -p ~/.local/bin
 - export PATH=~/.local/bin:$PATH
 - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.1.0/stack-0.1.1.0-x86_64-linux.gz | gunzip > ~/.local/bin/stack
 - chmod a+x ~/.local/bin/stack
 - cat /proc/cpuinfo | grep name

 - if ! [ -f ~/.local/include/hpx/hpx.h ] ; then ./.grab_hpx_1.0.sh ~/.local/; fi
 - find ~/.local/
 - export LD_LIBRARY_PATH=~/.local/lib:$LD_LIBRARY_PATH
 - export C_INCLUDE_PATH=~/.local/include:$C_INCLUDE_PATH

install:
 - stack setup --no-terminal +RTS -N1 -RTS
 - stack test --only-snapshot --no-terminal +RTS -N1 -RTS

script:
#  - stack test --no-terminal +RTS -N1 -RTS
  - stack build --no-terminal +RTS -N1 -RTS

git:
  submodules: false
