language: haskell

sudo: false
cache:
  directories:
  - $HOME/.stack/
  - $HOME/.local/

before_install:
 - mkdir -p $HOME/.local/bin
 - export PATH=$HOME/.local/bin:$PATH
 - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.1.0/stack-0.1.1.0-x86_64-linux.gz | gunzip > $HOME/.local/bin/stack
 - chmod a+x $HOME/.local/bin/stack
 - cat /proc/cpuinfo | grep name

 - if ! [ -f $HOME/.local/include/hpx/hpx.h ] ; then ./.grab_hpx_1.3.sh $HOME/.local/; fi
 - find $HOME/.local/
 - export PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH
 - export LD_LIBRARY_PATH=$HOME/.local/lib:$LD_LIBRARY_PATH
 - export C_INCLUDE_PATH=#HOME/.local/include:$C_INCLUDE_PATH

install:
 - stack setup --no-terminal +RTS -N1 -RTS
 - stack test --only-snapshot --no-terminal +RTS -N1 -RTS

script:
  - stack test --extra-include-dirs="$HOME/.local/include/" --extra-lib-dirs="$HOME/.local/lib/" --no-terminal +RTS -N1 -RTS

git:
  submodules: false
