# This must be one that the corresponding version of NixPkgs knows about:
resolver: lts-5.9

packages:
- '.'
- location:
    git: https://github.com/RyanGlScott/bindings-dsl.git
    commit: e918a9eea5b153c78f4a95c30262fdf917603d2c
  extra-dep: true
- location:
    git: https://github.com/iu-parfunc/bindings-hpx.git
    commit: 8a40caee411867101c90802fe4bd1166043a8712
  extra-dep: true

extra-deps:
- bindings-dsl-1.0.23
- bindings-hpx-0.1
- bindings-libffi-0.3

# [2015.09.19] Disabling for now and just running stack *inside* the
# docker image.  That way is safer currently.

nix:
  enable: true
  packages: [ hpx ]
#  shell-file: hpx-2.2.0.nix
#  shell-file: shell.nix

  # Use a specific tag of a specific NixPkgs:
#  path:  ["nixpkgs=https://github.com/iu-parfunc/nixpkgs/archive/hpx-2.2.0-nixpkgs-16.03.tar.gz"]

  path:  ["nixpkgs=https://github.com/iu-parfunc/nixpkgs/archive/hpx-master.tar.gz"]  
  

# docker:
#   enable: true
# #  repo: "fpco/stack-build"
#   repo: "haskell-hpx:1.0"
#   auto-pull: true
